use_frameworks!

platform :ios, '10.0'

target 'LJZ_CommonPage_Founction_Example' do
  pod 'LJZ_CommonPage_Founction', :path => '../'

  target 'LJZ_CommonPage_Founction_Tests' do
    inherit! :search_paths

    
  end
end
